### PR TITLE
Integrated google login in navBarWithGoogle.html

### PR DESCRIPTION
**Pull request by XiiinSheng**
### Integrated Google login into the navbar. 

**Created new files:**
* source/cards/navBarWithGoogle.html
* source/scripts/googleLogin.js

**Updates:**
* Copied navBar.html into navBarWithGoogle.html, changed components and corresponding styles. 
* Added login/signOut functions for Google profile data access and display. Profile data is printed out in the console.  

**Notes:**
* Google API doesn't allow `0.0.0.0` or `127.0.0.1`, so use `localhost:<port>` instead.

### CODE REVIEW

**Comment by celiaxiao** [comment]
Could you put all interactions with Google API outside the `scripts` folder and put them in the `service` folder instead?

**Comment by XiiinSheng** [comment]
Right now the google auth gives error `idpiframe_initialization_failed` on GitHub page. Working on debugging.

**Comment by XiiinSheng** [comment]
Working on coding style and frontend/backend migration. PLEASE DON'T MERGE.

**Comment by XiiinSheng** [comment]
**Updates:**
Split frontend and backend parts. Frontend modifies html components and passes data to backend, backend makes Google API calls. 

Created functions in `service/user/googleLogin.js`: 
```
userSignedIn(profile)
userSignedOut()
```
Created skeletons: 
```
hasUser(email)
createNewUser(profile)
getUserData(email)
```

**Review by celiaxiao — APPROVED** [review]
Well done!

**Review by Skarlys — APPROVED** [review]
Amazing!!

**Pull request merged**
